import Head from "next/head";
import Image from "next/image";
import Login from "../components/login/login";
import { useUserContext } from "../libs/user-context";
import styles from "../styles/Home.module.css";
import { Center, Text } from "@chakra-ui/react";
import UserProfile from "../components/user/user-profile";
import axiosApiInstance from "../libs/axios";
import { useEffect, useState } from "react";

export default function Home() {
  const { user, login } = useUserContext();

  const TodoList = () => {
    const [todos, setTodos] = useState([]);

    useEffect(() => {
      axiosApiInstance
        .get(`${process.env.NEXT_PUBLIC_API_ENDPOINT}/todos`)
        .then((res) => {
          console.log(res);
          setTodos(res.data);
        });
    }, []);

    return (
      <>
        <ul>
          {todos.map((todo) => {
            return <li key={todo.ID}>{todo.title}</li>;
          })}
        </ul>
      </>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {user?.displayName} to{" "}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {!user && (
          <>
            <Center p={"1rem"}>
              <Login />
            </Center>
          </>
        )}

        {user && (
          <>
            <UserProfile />
            <TodoList />
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
